//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterUnit
    {
        public int Id { get; set; }
        public byte CompanyCode { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string CrushingSeason { get; set; }
        public Nullable<System.TimeSpan> ReportStartTime { get; set; }
        public Nullable<System.DateTime> CrushingStartDate { get; set; }
        public Nullable<System.DateTime> CrushingEndDate { get; set; }
        public Nullable<int> DayHours { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string NewMillCapacity { get; set; }
        public string OldMillCapacity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Createdy { get; set; }
    }
}
